# Generated by Django 4.1 on 2022-08-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('agent_id', models.CharField(max_length=10)),
                ('agent_name', models.TextField(max_length=255)),
                ('type', models.TextField(max_length=255)),
                ('client_name', models.TextField(max_length=255)),
                ('client_phone', models.CharField(max_length=10)),
                ('hour', models.TimeField()),
            ],
        ),
    ]
