# Generated by Django 4.1 on 2022-08-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='country',
            field=models.CharField(default='Country', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='agent_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='client_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='client_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(),
        ),
    ]
